FROM shadowrobot/dexterous-hand:kinetic-night-build

LABEL Description="This ROS Kinetic image contains Shadow's dexterous hand software with sr_benchmarking repo. It includes IDE environments." Vendor="Shadow Robot" Version="1.0"

USER user

RUN cd /home/user/projects/shadow_robot/base_deps/src && \
    source /home/user/projects/shadow_robot/base_deps/devel/setup.bash && \
    git clone https://github.com/shadow-robot/sr_benchmarking.git && \
    git clone https://github.com/ros-planning/moveit_resources.git && \
    roscd moveit && \
    git checkout F_improving_exporting_importing_from_warehouse && \
    cd /home/user/projects/shadow_robot/base_deps/ && \
    catkin_make

USER root

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/usr/bin/terminator"]

